/**
 * End-to-end tests for the PDF signature pipeline using a self-signed test
 * certificate chain generated by scripts/generate-test-pdf.mjs.
 *
 * Run fixtures generation first:
 *   node scripts/generate-test-pdf.mjs
 *
 * Then run tests:
 *   npx vitest run
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import forge from 'node-forge';
import { extractPDFSignature, verifySignature, isPdfEncrypted } from '../pdfSignature';
import { decryptPDF } from '../pdfSignature';

const __dirname = dirname(fileURLToPath(import.meta.url));
const FIXTURES  = join(__dirname, 'fixtures');
const IGNORE    = join(__dirname, '../../.ignore');

const SIGNED_PDF     = join(FIXTURES, 'test-signed.pdf');
const ROOT_CERT_PEM  = join(FIXTURES, 'test-root-cert.pem');
const ENCRYPTED_PDF  = join(IGNORE,   'test_signed_7char.pdf');

function fixturesExist() {
  return existsSync(SIGNED_PDF) && existsSync(ROOT_CERT_PEM);
}

describe('PDF signature pipeline', () => {
  beforeAll(() => {
    if (!fixturesExist()) {
      throw new Error(
        'Test fixtures missing. Run: node scripts/generate-test-pdf.mjs'
      );
    }
  });

  it('extracts ByteRange and signature bytes from the signed PDF', () => {
    const pdfBytes = new Uint8Array(readFileSync(SIGNED_PDF));
    const { signedData, sigBytes, byteRange } = extractPDFSignature(pdfBytes);

    expect(byteRange).toHaveLength(4);
    expect(byteRange[0]).toBe(0);            // b0 is always 0
    expect(byteRange[1]).toBeGreaterThan(0); // b1: end of signed range 1
    expect(byteRange[2]).toBeGreaterThan(byteRange[1]); // b2 > b1
    expect(byteRange[3]).toBeGreaterThan(0); // b3: length of signed range 2
    expect(signedData.length).toBe(byteRange[1] + byteRange[3]);
    expect(sigBytes.length).toBeGreaterThan(0);
  });

  it('verifies the PKCS#7 signature using the custom test root certificate', async () => {
    const pdfBytes   = new Uint8Array(readFileSync(SIGNED_PDF));
    const rootPem    = readFileSync(ROOT_CERT_PEM, 'utf8');

    const { signedData, sigBytes } = extractPDFSignature(pdfBytes);
    const result = await verifySignature(signedData, sigBytes, forge, [rootPem]);

    expect(result.verified).toBe(true);
    expect(result.chainVerified).toBe(true);
    expect(result.signatureVerified).toBe(true);
    expect(result.hasUIDAI).toBe(true); // cert CN contains "Unique Identification Authority"
    expect(result.certCount).toBeGreaterThanOrEqual(2); // root + signing cert
  });

  it('reports the correct signer certificate subject', async () => {
    const pdfBytes = new Uint8Array(readFileSync(SIGNED_PDF));
    const rootPem  = readFileSync(ROOT_CERT_PEM, 'utf8');

    const { signedData, sigBytes } = extractPDFSignature(pdfBytes);
    const result = await verifySignature(signedData, sigBytes, forge, [rootPem]);

    expect(result.signerCertInfo.subjectCN).toContain('Unique Identification Authority of India');
    expect(result.signerCertInfo.subjectO).toContain('Unique Identification Authority of India');
  });

  it('fails verification when given the wrong trusted root', async () => {
    const pdfBytes = new Uint8Array(readFileSync(SIGNED_PDF));

    // Generate a different (unrelated) root cert
    const otherKeys = forge.pki.rsa.generateKeyPair(1024);
    const otherCert = forge.pki.createCertificate();
    otherCert.publicKey = otherKeys.publicKey;
    otherCert.serialNumber = '99';
    otherCert.validity.notBefore = new Date();
    otherCert.validity.notAfter  = new Date(Date.now() + 1000 * 60 * 60);
    otherCert.setSubject([{ name: 'commonName', value: 'Wrong Root' }]);
    otherCert.setIssuer([{ name: 'commonName', value: 'Wrong Root' }]);
    otherCert.sign(otherKeys.privateKey, forge.md.sha256.create());
    const wrongPem = forge.pki.certificateToPem(otherCert);

    const { signedData, sigBytes } = extractPDFSignature(pdfBytes);
    const result = await verifySignature(signedData, sigBytes, forge, [wrongPem]);

    expect(result.verified).toBe(false);
    expect(result.chainVerified).toBe(false);
  });

  it('detects the test PDF as unencrypted', () => {
    const pdfBytes = new Uint8Array(readFileSync(SIGNED_PDF));
    expect(isPdfEncrypted(pdfBytes)).toBe(false);
  });

  describe('encrypted PDF (password: RIA1999 — 7 characters)', () => {
    it('detects the encrypted PDF as encrypted', () => {
      if (!existsSync(ENCRYPTED_PDF)) return; // skip if not generated
      const pdfBytes = new Uint8Array(readFileSync(ENCRYPTED_PDF));
      expect(isPdfEncrypted(pdfBytes)).toBe(true);
    });

    it('decrypts successfully with a 7-character password', async () => {
      if (!existsSync(ENCRYPTED_PDF)) return;
      const pdfBytes = new Uint8Array(readFileSync(ENCRYPTED_PDF));
      const decrypted = await decryptPDF(pdfBytes, 'RIA1999');

      expect(decrypted).toBeInstanceOf(Uint8Array);
      expect(decrypted.length).toBeGreaterThan(0);
      // Decrypted output should be a valid PDF
      const header = new TextDecoder().decode(decrypted.slice(0, 5));
      expect(header).toBe('%PDF-');
    });

    it('rejects an incorrect password', async () => {
      if (!existsSync(ENCRYPTED_PDF)) return;
      const pdfBytes = new Uint8Array(readFileSync(ENCRYPTED_PDF));
      await expect(decryptPDF(pdfBytes, 'WRONG123')).rejects.toThrow();
    });
  });
});
